export const SAVE_PHONE_NUMBER = 'SAVE_PHONE_NUMBER';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
export const SAVE_CODE_ERROR_MESSAGE = 'SAVE_CODE_ERROR_MESSAGE';
export const SAVE_CODE_SUCCESS = 'SAVE_CODE_SUCCESS';

